---
title: "Final Report"
author: "Noah Estrada-Rand, Brady Hoskins, Charles Filce"
date: "12/12/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(forcats)
library(tidyverse)
library(summarytools)
library(corrplot)
library(ggplot2)
library(glmnet)
library(glmnetUtils)
library(randomForest)
library(randomForestExplainer)
library(caret)
library(plotROC)
library(PRROC)
library(gmodels)
library(tree)
```

## Data Cleaning

```{r}
####cleaning the data 
steam <- read.csv("steam.csv")
nrow(steam[!complete.cases(steam),])
steam$price <- steam$price *1.28
steam<- subset(steam, select = -c(appid,english,steamspy_tags,
                                  name,release_date,
                                  platforms,publisher,developer))
steam$genres <- do.call('rbind',strsplit(as.character(steam$genres), ';', fixed=TRUE))[,1]
steam$categories <- do.call('rbind',strsplit(as.character(steam$categories), ';', fixed=TRUE))[,1]
steam$categories <- as.factor(steam$categories)
steam$genres <- as.factor(steam$genres)
steam <- steam[steam$average_playtime < 100000,]
steam <- steam[steam$price <50,]
steam <- steam[steam$average_playtime < 40000,]
steam <- steam[steam$negative_ratings < 2e+05,]
steam <- steam[steam$positive_ratings < 1e+06,]
steam$simple_categories <- fct_lump(steam$categories,n = 4)
steam$categories <- ifelse(steam$categories == "Single-player","SinglePlayer",
                           ifelse(steam$categories == "Multi-player","Multi-Player",
                                  ifelse(steam$categories == "Online Multi-Player","Multi-Player",
                                         ifelse(steam$categories == "Local Multi-Player","Multi-Player",
                                                ifelse(steam$categories == "MMO","MMO",
                                                       ifelse(steam$categories == "Co-op","Co-op",
                                                              ifelse(steam$categories == "Shared/Split Screen","Co-op",
                                                                     ifelse(steam$categories == "Local Co-op","Co-op",
                                                                            ifelse(steam$categories == "Online Co-op","Co-op",
                                                                                   ifelse(steam$categories == "Steam Cloud","Steam",
                                                                                          ifelse(steam$categories == "Steam Trading Cards","Steam",
                                                                                                 ifelse(steam$categories == "Steam Leaderboards","Steam",
                                                                                                        ifelse(steam$categories == "Steam Achievements","Steam","Other")))))))))))))
steam$categories <- as.factor(steam$categories)
steam$genres <- fct_lump(steam$genres,n = 5)
steam$successfulGame <- ifelse(steam$owners == "10000000-20000000",1,
                               ifelse(steam$owners == "20000000-50000000",1,
                                      ifelse(steam$owners == "50000000-100000000",1,
                                             ifelse(steam$owners == "100000000-200000000",1,
                                                    ifelse(steam$owners == "5000000-10000000",1,
                                                           ifelse(steam$owners == "2000000-5000000",1,
                                                                  ifelse(steam$owners == "1000000-2000000",1,0)))))))

steam <- subset(steam, select = -c(owners,categories,positive_ratings,negative_ratings,
                                   median_playtime))
steam$required_age <- as.factor(steam$required_age)
```
# Summary Statistics

## Sample of Data

```{r}
head(steam,5)
```
## Descriptive Statistics

```{r}
descr(steam)
```
## Correlation Matrix

```{r,echo = FALSE}
numeric_cols <- sapply(steam,is.numeric)
correlations <- cor(steam[,numeric_cols])
corrplot(correlations)
```

## Summary Plots
```{r,echo=FALSE}
ggplot(steam,aes(x = achievements,y = average_playtime)) + geom_point(aes(color = successfulGame))+
  geom_smooth() + labs(x = "Number of In-Game Achievements",y = "Average Playtime (hrs)",
                       title = "Plotted Achievements and Average Playtime")
```

```{r,echo=FALSE}
ggplot(steam,aes(x = price,y = average_playtime)) + 
  geom_point(aes(color = successfulGame)) + 
  labs(x = "Price of the Game (dollars)",y ="Average Playtime (hrs)",
       title = "Average Playtime Plotted Against Price of Game")
```

```{r,echo = FALSE}
boxplot(steam$average_playtime~steam$required_age,
        main = "Average Playtime by Required Age",xlab = "Required Age (years)",
        ylab = "Average Playtime")
```

```{r,echo = FALSE}
ggplot(steam,aes(x = genres,y = price)) + geom_boxplot() + 
  labs(title = "Boxplots of Price By Genre",x = "Genres",y = "Price (dollars)")
```


##Logistic Model

```{r,echo = FALSE}
set.seed(2019)
train_index <- sample(1:nrow(steam),.75*nrow(steam),replace = FALSE)
steam_train <- steam[train_index,]
steam_test <- steam[-train_index,]
steam_logit <- glm(successfulGame~price+relevel(genres,ref = "Other") + required_age+
                     average_playtime,
                   data = steam_train,
                   family = "binomial")
steam_train$logit_preds <- predict(steam_logit,type = "response")
steam_test$logit_preds <- predict(steam_logit,newdata = steam_test,
                                  type = "response")
steam_train$pred_class <- ifelse(steam_train$logit_preds >.04,1,0)
steam_test$pred_class <-ifelse(steam_test$logit_preds>.04,1,0)
summary(steam_logit)
```
```{r}
exp(steam_logit$coefficients)
```
## ROC Plots

```{r,echo = FALSE}

train_ROC <- ggplot(steam_train,aes(m = logit_preds,
                                    d = successfulGame)) +
  geom_roc(labelsize = 3.5,
           cutoffs.at = c(.99,.9,.7,.6,.5,.4,.1,.01)) +
  labs(title = "ROC Curve for Train Data",x = "False Positive Fraction",
       y= "True Positive Fraction")
test_ROC <- ggplot(steam_test,aes(m = logit_preds,
                                  d = successfulGame)) +
  geom_roc(labelsize = 3.5,
           cutoffs.at = c(.99,.9,.7,.6,.5,.4,.1,.01)) +
  labs(title = "ROC Curve for Test Data",x = "False Positive Fraction",
       y= "True Positive Fraction")
train_ROC
test_ROC
```
## Confusion Matrices

```{r,echo = FALSE}
print("Train Confusion Matrix")
CrossTable(steam_train$pred_class,steam_train$successfulGame,
           prop.r = FALSE,
           prop.c = FALSE,
           prop.t = FALSE,
           prop.chisq = FALSE)
print("Accuracy: 94.8%") 
print("Sensitivity: 46%")
print("Specificity: 95.7%")

```

```{r,echo = FALSE}
print("Test Confusion Matrix")
CrossTable(steam_test$pred_class,steam_test$successfulGame,
           prop.r = FALSE,
           prop.c = FALSE,
           prop.t = FALSE,
           prop.chisq = FALSE)
print("Accuracy: 94.9%") 
print("Sensitivity: 51%")
print("Specificity: 95.7%")
```


## Random Forest Model

```{r,echo = FALSE}
steam$successfulGame <- as.factor(steam$successfulGame)

set.seed(2019)
train_idx <- sample(1:nrow(steam), size = floor(.75 * nrow(steam)))
steam_train <- steam[train_idx,]
steam_test <- steam[-train_idx,]

random_forest_steam <- randomForest(successfulGame~.,
                                    data = steam_train,
                                    mtry = 2,
                                    ntrees = 500,
                                    type = classification,
                                    importance = TRUE)
random_forest_preds <- predict(random_forest_steam,type = "response")
preds_2 <- data.frame(steam_train,preds= random_forest_preds)
preds_test_2 <-data.frame(steam_test,preds = predict(random_forest_steam,
                                                     newdata = steam_test,
                                                     type = "response"))
summary(random_forest_steam)
varImpPlot(random_forest_steam)
```
##Confusion Matrices

```{r,echo = FALSE}
print("Train Confusion Matrix")
CrossTable(preds_2$successfulGame,preds_2$preds,
           prop.r = FALSE,
           prop.c = FALSE,
           prop.t = FALSE,
           prop.chisq = FALSE)
print("Accuracy: 98.1%")
print("Sensitivity: 60.6%")
print("Specificity: 98.4")

print("Test Confusion Matrix")
CrossTable(preds_test_2$successfulGame,preds_test_2$preds,
           prop.r = FALSE,
           prop.c = FALSE,
           prop.t = FALSE,
           prop.chisq = FALSE)
print("Accuracy: 98.3%")
print("Sensitivity: 75%")
print("Specificity: 98.4")
```

## Pruned Tree Model

```{r,echo =FALSE}
steam$successfulGame <- as.factor(steam$successfulGame)

set.seed(2019)
train_idx <- sample(1:nrow(steam), size = floor(.75 * nrow(steam)))
steam_train <- steam[train_idx,]
steam_test <- steam[-train_idx,]
###tree based on the top 4 most important variables
steam_tree <- tree(successfulGame~.,
                   data = steam_train)
###cross validation
tree_cv <- cv.tree(steam_tree)
best_tree_index <- which.min(tree_cv$dev)
best_size <- tree_cv$size[best_tree_index]

####prune the tree
pruned_tree <- prune.tree(steam_tree,best = best_size)
plot(pruned_tree)
text(pruned_tree,pretty=0)
```
## Confusion Matrices

```{r,echo =FALSE}
basic_preds_train <- data.frame(steam_train,preds = predict(pruned_tree,
                                                            type = "class"))
basic_preds_test <- data.frame(steam_test,preds = predict(pruned_tree,
                                                          newdata = steam_test,
                                                          type = "class"))
print("Train Confusion Matrix")
CrossTable(basic_preds_train$successfulGame,basic_preds_train$preds,
           prop.r = FALSE,
           prop.c = FALSE,
           prop.t = FALSE,
           prop.chisq = FALSE)
print("Accuracy: 98%")
print("Sensitivity: 42.9%")
print("Specificity: 98.3")

print("Test Conusion Matrix")
CrossTable(basic_preds_test$successfulGame, basic_preds_test$preds,
           prop.r = FALSE,
           prop.c = FALSE,
           prop.t = FALSE,
           prop.chisq = FALSE)
print("Accuracy: 98.1%")
print("Sensitivity: 53.7%")
print("Specificity: 98.3")
```












